version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=n113kzufdrnjnwt2vk322kf8
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=siL9tfxbuwcIWdB4SfpyvlVq0xKcOKnr4unitTNM449sCgHgF9ARZwmm5u13EypK
      - JWT_SECRET=AHGwDAAO4J/e0FrHjnh/9vHcrIJ1cOC785IhFM2FWIA=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mg8Jn^#Cpe
      - SWAGGER_ENABLED=false
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_started
    networks:
      - securevault

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass mg8Jn^#Cpe
    networks:
      - securevault

networks:
  securevault:
    driver: bridge