version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`vault.tanay.pro`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    depends_on:
      - app
    networks:
      - securevault

  app:
    build: .
    expose:
      - "8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securevault
      - DB_USERNAME=postgres
      - DB_PASSWORD=mg8Jn^#Cpe
      - JWT_SECRET=AHGwDAAO4J/e0FrHjnh/9vHcrIJ1cOC785IhFM2FWIA=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mg8Jn^#Cpe
      - SWAGGER_ENABLED=false
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - securevault

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mg8Jn^#Cpe
      - POSTGRES_DB=securevault
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - securevault

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass mg8Jn^#Cpe
    networks:
      - securevault

volumes:
  postgres_data:

networks:
  securevault:
    driver: bridge
