import Foundation

/// Swift bridge to the Rust crypto-core static library.
///
/// Build the native library:
///   cd crypto-core && ./build-mobile.sh
///
/// Then add to Xcode:
///   1. Add `target/mobile/ios/libsecurevault_crypto_core.a` to "Link Binary With Libraries"
///   2. Add the C header (generated by cbindgen) to the bridging header
///   3. Set "Library Search Paths" to include the build output directory

@objc public class RustCryptoCore: NSObject {
    @objc public static let shared = RustCryptoCore()

    @objc public func deriveAuthHash(
        password: String,
        salt: String,
        iterations: Int32,
        memory: Int32,
        parallelism: Int32
    ) -> String {
        return password.withCString { pw in
            salt.withCString { s in
                let result = securevault_derive_auth_hash(pw, s, iterations, memory, parallelism)
                let str = String(cString: result!)
                securevault_free_string(result)
                return str
            }
        }
    }

    @objc public func deriveKek(
        password: String,
        saltB64: String,
        iterations: Int32,
        memory: Int32,
        parallelism: Int32
    ) -> Data {
        return password.withCString { pw in
            saltB64.withCString { s in
                let result = securevault_derive_kek(pw, s, iterations, memory, parallelism)
                let str = String(cString: result!)
                securevault_free_string(result)
                return Data(base64Encoded: str)!
            }
        }
    }
}

// C FFI declarations from the Rust crypto-core library
@_silgen_name("securevault_derive_auth_hash")
func securevault_derive_auth_hash(
    _ password: UnsafePointer<CChar>,
    _ salt: UnsafePointer<CChar>,
    _ iterations: Int32,
    _ memory: Int32,
    _ parallelism: Int32
) -> UnsafeMutablePointer<CChar>?

@_silgen_name("securevault_derive_kek")
func securevault_derive_kek(
    _ password: UnsafePointer<CChar>,
    _ saltB64: UnsafePointer<CChar>,
    _ iterations: Int32,
    _ memory: Int32,
    _ parallelism: Int32
) -> UnsafeMutablePointer<CChar>?

@_silgen_name("securevault_free_string")
func securevault_free_string(_ ptr: UnsafeMutablePointer<CChar>?)
