// SecureVault test vector generator
// Only generates AES-GCM vectors (deterministic across platforms).
// KDF (Argon2id) vectors are platform-specific — each platform tests
// against its own native binary (Rust .so/.a/.wasm).

const subtle = globalThis.crypto.subtle

const b64 = (bytes) => Buffer.from(bytes).toString('base64')
const unb64 = (s) => new Uint8Array(Buffer.from(s, 'base64'))
const utf8 = (s) => new TextEncoder().encode(s)

async function aesGcmEncrypt(keyBytes, iv, plaintextBytes) {
  const key = await subtle.importKey('raw', keyBytes, 'AES-GCM', false, ['encrypt'])
  const ct = await subtle.encrypt({ name: 'AES-GCM', iv, tagLength: 128 }, key, plaintextBytes)
  return new Uint8Array(ct)
}

// Fixed test inputs (deterministic across all platforms)
const KEK_RAW = unb64('504NmZdCQp2PNGAZA5gq3vh1rwcT/pVLXWHDcJlf18w=')
const VAULT_KEY = new Uint8Array(32).map((_, i) => i)
const NONCE = new Uint8Array(12).map((_, i) => 0xa0 + i)
const ENTRY_JSON = '{"password":"hunter2","title":"Example","url":"https://example.com","username":"alice"}'

const cases = []

// Envelope A — wrapped vault key
const wrappedCt = await aesGcmEncrypt(KEK_RAW, NONCE, VAULT_KEY)
const wrappedCombined = new Uint8Array(12 + wrappedCt.length)
wrappedCombined.set(NONCE, 0)
wrappedCombined.set(wrappedCt, 12)
cases.push({
  name: 'envelope_a/wrap_vault_key',
  op: 'wrap_vault_key',
  input: { kek_raw_b64: b64(KEK_RAW), vault_key_raw_b64: b64(VAULT_KEY), nonce_b64: b64(NONCE) },
  expected: { wrapped_b64: b64(wrappedCombined) },
})

// Envelope B — entry encryption
const entryCt = await aesGcmEncrypt(VAULT_KEY, NONCE, utf8(ENTRY_JSON))
cases.push({
  name: 'envelope_b/encrypt_entry',
  op: 'encrypt_entry',
  input: { vault_key_raw_b64: b64(VAULT_KEY), plaintext_json: ENTRY_JSON, nonce_b64: b64(NONCE) },
  expected: { encrypted_data: 'v1:' + b64(entryCt), iv: b64(NONCE) },
})

// Envelope C — field encryption
const fieldPt = 'hunter2'
const fieldCt = await aesGcmEncrypt(VAULT_KEY, NONCE, utf8(fieldPt))
const fieldCombined = new Uint8Array(12 + fieldCt.length)
fieldCombined.set(NONCE, 0)
fieldCombined.set(fieldCt, 12)
cases.push({
  name: 'envelope_c/encrypt_field',
  op: 'encrypt_field',
  input: { vault_key_raw_b64: b64(VAULT_KEY), plaintext: fieldPt, nonce_b64: b64(NONCE) },
  expected: { ciphertext: 'v1:' + b64(fieldCombined) },
})

process.stdout.write(JSON.stringify({
  _description: 'SecureVault crypto-core golden vectors (v2 format). Generated by generate.mjs — do not hand-edit.',
  _notes: 'AES-GCM only. KDF vectors excluded due to platform-specific Argon2id variance.',
  encryption_version: 2,
  base64: 'standard (RFC 4648, not url-safe), no padding stripping',
  vectors: cases,
}, null, 2) + '\n')
