import { createHmac } from 'crypto'

let argon2id = null
try {
  ;({ argon2id } = await import('hash-wasm'))
} catch {
  console.error('[warn] hash-wasm not installed — emitting envelope/AES vectors only (no KDF vectors).')
}

const subtle = globalThis.crypto.subtle

const b64 = (bytes) => Buffer.from(bytes).toString('base64')
const unb64 = (s) => new Uint8Array(Buffer.from(s, 'base64'))
const utf8 = (s) => new TextEncoder().encode(s)

function hkdfExpand(keyBytes, info) {
  // HKDF-Expand single block: HMAC-SHA256(key, info || 0x01)
  return createHmac('sha256', Buffer.from(keyBytes)).update(info).update(Buffer.from([1])).digest()
}

async function aesGcmEncrypt(keyBytes, iv, plaintextBytes) {
  const key = await subtle.importKey('raw', keyBytes, 'AES-GCM', false, ['encrypt'])
  const ct = await subtle.encrypt({ name: 'AES-GCM', iv, tagLength: 128 }, key, plaintextBytes)
  return new Uint8Array(ct)
}

async function argon(password, saltBytes, p) {
  return argon2id({
    password,
    salt: saltBytes,
    parallelism: p.parallelism,
    iterations: p.iterations,
    memorySize: p.memory_kib,
    hashLength: 32,
    outputType: 'binary',
  })
}

const PARAMS = { iterations: 3, memory_kib: 98304, parallelism: 4 }
const PASSWORD = 'correct horse battery staple'
const SALT_B64 = b64(utf8('0123456789abcdef'))
const AUTH_SALT_B64 = b64(utf8('auth-salt-fixed-string'))
const VAULT_KEY = new Uint8Array(32).map((_, i) => i)
const NONCE = new Uint8Array(12).map((_, i) => 0xa0 + i)
const ENTRY_JSON = '{"password":"hunter2","title":"Example","url":"https://example.com","username":"alice"}'

const cases = []

let masterKey, kek
if (argon2id) {
  masterKey = await argon(PASSWORD, unb64(SALT_B64), PARAMS)

  // Auth hash: HKDF-Expand(MasterKey, "securevault-auth")
  const authHash = hkdfExpand(masterKey, 'securevault-auth')
  cases.push({
    name: 'auth_hash/default-params',
    op: 'derive_auth_hash',
    params: PARAMS,
    input: { password: PASSWORD, salt_b64: AUTH_SALT_B64 },
    expected: { auth_hash_b64: b64(authHash) },
  })

  // KEK: HKDF-Expand(MasterKey, "securevault-kek")
  kek = hkdfExpand(masterKey, 'securevault-kek')
  cases.push({
    name: 'kek/default-params',
    op: 'derive_kek',
    params: PARAMS,
    input: { password: PASSWORD, salt_b64: SALT_B64 },
    expected: { kek_raw_b64: b64(kek) },
  })
} else {
  kek = new Uint8Array(32).map((_, i) => 0x40 + i)
}

const wrappedCt = await aesGcmEncrypt(kek, NONCE, VAULT_KEY)
const wrappedCombined = new Uint8Array(12 + wrappedCt.length)
wrappedCombined.set(NONCE, 0)
wrappedCombined.set(wrappedCt, 12)
cases.push({
  name: 'envelope_a/wrap_vault_key',
  op: 'wrap_vault_key',
  input: { kek_raw_b64: b64(kek), vault_key_raw_b64: b64(VAULT_KEY), nonce_b64: b64(NONCE) },
  expected: { wrapped_b64: b64(wrappedCombined) },
})

const entryCt = await aesGcmEncrypt(VAULT_KEY, NONCE, utf8(ENTRY_JSON))
cases.push({
  name: 'envelope_b/encrypt_entry',
  op: 'encrypt_entry',
  input: { vault_key_raw_b64: b64(VAULT_KEY), plaintext_json: ENTRY_JSON, nonce_b64: b64(NONCE) },
  expected: { encrypted_data: 'v1:' + b64(entryCt), iv: b64(NONCE) },
})

const fieldPt = 'hunter2'
const fieldCt = await aesGcmEncrypt(VAULT_KEY, NONCE, utf8(fieldPt))
const fieldCombined = new Uint8Array(12 + fieldCt.length)
fieldCombined.set(NONCE, 0)
fieldCombined.set(fieldCt, 12)
cases.push({
  name: 'envelope_c/encrypt_field',
  op: 'encrypt_field',
  input: { vault_key_raw_b64: b64(VAULT_KEY), plaintext: fieldPt, nonce_b64: b64(NONCE) },
  expected: { ciphertext: 'v1:' + b64(fieldCombined) },
})

process.stdout.write(JSON.stringify({
  _description: 'SecureVault crypto-core golden vectors (v2 format). Generated by generate.mjs — do not hand-edit.',
  encryption_version: 2,
  base64: 'standard (RFC 4648, not url-safe), no padding stripping',
  vectors: cases,
}, null, 2) + '\n')
